[package]
name = "percolation-simulation"
version = "0.2.1"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false

[dependencies]
iced = { version = "0.4.0", features = ["canvas"] }
rand = "*"
